%RUN_TESTS Run MATLAB-side smoke checks without connecting to a vehicle.
root = fileparts(fileparts(mfilename('fullpath')));
required = {
    'yunlink_connect.m', 'yunlink_vehicle.m', 'yunlink_state.m', ...
    'yunlink_state_raw.m', 'yunlink_takeoff.m', 'yunlink_move_to.m', ...
    'yunlink_position_control.m', 'yunlink_velocity_control.m', ...
    'yunlink_waypoint.m', 'yunlink_hover.m', 'yunlink_return_home.m', ...
    'yunlink_cancel.m', 'yunlink_land.m', 'yunlink_emergency_lock.m', ...
    'yunlink_command.m', 'yunlink_monitor.m', 'yunlink_setup.m', ...
    'yunlink_update.m', 'yunlink_examples.m', 'yunlink_discover.m', ...
    'yunlink_entities.m', 'yunlink_ugv.m', 'yunlink_ugv_state.m', ...
    'yunlink_ugv_move_to.m', 'yunlink_ugv_velocity.m', 'yunlink_ugv_hold.m', ...
    'yunlink_translate.m', 'yunlink_waypoints.m'};
docs = {'README.md', 'INSTALL.txt', 'getting_started.html', 'getting_started.m'};
examples = { ...
    'examples/00_setup.m', 'examples/01_discover.m', 'examples/02_connect_and_inspect.m', ...
    'examples/03_watch_state.m', 'examples/04_flight_basics.m', 'examples/05_waypoints.m', ...
    'examples/06_cancel_action.m', 'examples/07_ugv_control.m', 'examples/08_errors.m', ...
    'examples/10_discover_select_connect.m', 'examples/11_multi_device_control.m', ...
    'examples/12_multi_uav_waypoints.m', 'examples/13_multi_device_state.m', ...
    'examples/14_observe_live.m', 'examples/read_state_demo.m', ...
    'examples/basic_flight_demo.m', 'examples/README.md'};
developer = {'developer/README.md', 'developer/build_release_bundle.m', ...
    'developer/package_release.sh', 'developer/release_notes.md', ...
    'build_toolbox.m', 'yunlink_sunray.prj', 'tests/home_connectivity.m'};
for index = 1:numel(required)
    assert(isfile(fullfile(root, required{index})), ...
        'Missing MATLAB wrapper: %s', required{index});
end
for index = 1:numel(docs)
    assert(isfile(fullfile(root, docs{index})), ...
        'Missing user documentation: %s', docs{index});
end
for index = 1:numel(examples)
    assert(isfile(fullfile(root, examples{index})), ...
        'Missing MATLAB example: %s', examples{index});
end
for index = 1:numel(developer)
    assert(isfile(fullfile(root, developer{index})), ...
        'Missing MATLAB packaging file: %s', developer{index});
end

% These controls are intentionally absent: arm/disarm are read-only state.
assert(~isfile(fullfile(root, 'yunlink_arm.m')));
assert(~isfile(fullfile(root, 'yunlink_disarm.m')));

setupSource = fileread(fullfile(root, 'yunlink_setup.m'));
assert(contains(setupSource, 'nargin == 0'), ...
    'yunlink_setup must support the no-argument wizard.');
assert(contains(setupSource, 'uigetfile'), ...
    'yunlink_setup wizard must use MATLAB file selection.');
assert(contains(setupSource, 'Select bundle folder'', ''Select wheel'', ''Skip'', ''Select bundle folder''') || ...
    contains(setupSource, "'Select bundle folder', 'Select wheel', 'Skip', 'Select bundle folder'"), ...
    'yunlink_setup binding dialog must be a 3-button questdlg with an explicit default.');
assert(contains(setupSource, 'cp314') || contains(setupSource, '3.14'), ...
    'yunlink_setup must reject MATLAB Python 3.14 with a visible message.');
assert(contains(setupSource, '3.13'), ...
    'yunlink_setup must accept Python 3.13.');
assert(contains(setupSource, 'cp313'), ...
    'yunlink_setup must match Python 3.13 wheels.');
assert(~contains(setupSource, '3.10+'), ...
    'yunlink_setup must list 3.10-3.13 explicitly.');
assert(~contains(setupSource, 'yunlink_connect('), ...
    'yunlink_setup must not connect to a vehicle.');
assert(contains(setupSource, 'yunlink_examples'), ...
    'yunlink_setup must offer to open the MATLAB example folder.');
exampleOpener = fileread(fullfile(root, 'yunlink_examples.m'));
assert(contains(exampleOpener, 'filebrowser'), ...
    'yunlink_examples must show MATLAB Current Folder.');
assert(contains(exampleOpener, '00_setup.m') || contains(exampleOpener, 'read_state_demo.m'), ...
    'yunlink_examples must surface the setup or read-only demo.');
setupExample = fileread(fullfile(root, 'examples', '00_setup.m'));
assert(contains(setupExample, 'pythonExe') && contains(setupExample, 'bundleDir'), ...
    '00_setup.m must let the user fill python and bundle paths.');
assert(contains(fileread(fullfile(root, 'yunlink_setup.m')), 'clean_env_prefix'), ...
    'yunlink_setup must isolate MATLAB library paths when invoking pip.');

userGuide = fileread(fullfile(root, 'README.md'));
assert(contains(userGuide, '双击') && contains(userGuide, '.mltbx'), ...
    'User guide must document double-clicking the .mltbx installer.');
assert(contains(userGuide, 'Add Package Repository'), ...
    'User guide must distinguish package repositories from .mltbx installation.');
assert(contains(userGuide, 'Windows') && contains(userGuide, 'Linux'), ...
    'User guide must cover Windows, macOS, and Linux.');
assert(contains(userGuide, '00_setup.m'), ...
    'User guide must point at 00_setup.m.');
assert(~contains(userGuide, '/Users/groove'), ...
    'User guide must not include a machine-specific home path.');

packSource = fileread(fullfile(root, 'build_toolbox.m'));
assert(contains(packSource, 'getting_started.html'));
assert(contains(packSource, 'getting_started.m'));
assert(contains(packSource, 'ToolboxFiles'));
assert(contains(packSource, 'vendor'));

demoSource = fileread(fullfile(root, 'examples', 'basic_flight_demo.m'));
assert(contains(demoSource, 'sends flight commands') || contains(demoSource, 'flight commands'));
readSource = fileread(fullfile(root, 'examples', 'read_state_demo.m'));
assert(contains(readSource, 'does not send flight commands'));

% Parse every wrapper so syntax errors are caught even in a no-device run.
addpath(root);
for index = 1:numel(required)
    [folder, name] = fileparts(required{index}); %#ok<ASGLU>
    assert(exist(name, 'file') == 2, 'MATLAB cannot resolve %s', name);
end
assert(exist('build_toolbox', 'file') == 2, 'MATLAB cannot resolve build_toolbox');
fprintf('YunLink MATLAB smoke checks passed (%d wrappers).\n', numel(required));
