%RUN_TESTS Run MATLAB-side smoke checks without connecting to a vehicle.
root = fileparts(fileparts(mfilename('fullpath')));
required = {
    'yunlink_connect.m', 'yunlink_vehicle.m', 'yunlink_state.m', ...
    'yunlink_state_raw.m', 'yunlink_takeoff.m', 'yunlink_move_to.m', ...
    'yunlink_position_control.m', 'yunlink_velocity_control.m', ...
    'yunlink_waypoint.m', 'yunlink_hover.m', 'yunlink_return_home.m', ...
    'yunlink_cancel.m', 'yunlink_land.m', 'yunlink_emergency_lock.m', ...
    'yunlink_command.m', 'yunlink_monitor.m', 'yunlink_setup.m', ...
    'yunlink_update.m', 'yunlink_examples.m', 'yunlink_discover.m', ...
    'yunlink_entities.m', 'yunlink_ugv.m', 'yunlink_ugv_state.m', ...
    'yunlink_ugv_move_to.m', 'yunlink_ugv_velocity.m', 'yunlink_ugv_hold.m', ...
    'yunlink_translate.m', 'yunlink_waypoints.m', 'yunlink_prepare_runtime.m', ...
    'yunlink_ensure_python.m', 'yunlink_mapping_start.m', 'yunlink_mapping_stop.m', ...
    'yunlink_example_target.m', 'yunlink_example_pick.m', ...
    'yunlink_load_example_env.m', 'yunlink_print_catalog.m', ...
    'yunlink_live_check.m'};
docs = {'README.md', 'INSTALL.txt', 'getting_started.html', 'getting_started.m'};
examples = { ...
    'examples/ex00_setup.m', 'examples/ex01_discover.m', 'examples/ex02_connect_and_inspect.m', ...
    'examples/ex03_watch_state.m', 'examples/ex04_flight_basics.m', 'examples/ex05_cancel_action.m', ...
    'examples/ex06_ugv_control.m', 'examples/ex07_errors.m', ...
    'examples/ex08_discover_select_connect.m', 'examples/ex09_multi_device_control.m', ...
    'examples/ex10_multi_device_state.m', 'examples/ex11_observe_live.m', ...
    'examples/ex12_live_check.m', 'examples/read_state_demo.m', ...
    'examples/basic_flight_demo.m', ...
    'examples/README.md', 'examples/yunlink.env.example'};
developer = {'developer/README.md', 'developer/API.md', 'developer/read_windows_debug.ps1', ...
    'developer/build_release_bundle.m', ...
    'developer/package_release.sh', 'developer/release_notes.md', ...
    'build_toolbox.m', 'yunlink_sunray.prj', 'tests/home_connectivity.m', ...
    'docs/yunlink-matlab-manual.typ', 'docs/README.md'};
for index = 1:numel(required)
    assert(isfile(fullfile(root, required{index})), ...
        'Missing MATLAB wrapper: %s', required{index});
end
for index = 1:numel(docs)
    assert(isfile(fullfile(root, docs{index})), ...
        'Missing user documentation: %s', docs{index});
end
for index = 1:numel(examples)
    assert(isfile(fullfile(root, examples{index})), ...
        'Missing MATLAB example: %s', examples{index});
end
for index = 1:numel(developer)
    assert(isfile(fullfile(root, developer{index})), ...
        'Missing MATLAB packaging file: %s', developer{index});
end

% These controls are intentionally absent: arm/disarm are read-only state.
assert(~isfile(fullfile(root, 'yunlink_arm.m')));
assert(~isfile(fullfile(root, 'yunlink_disarm.m')));

setupSource = fileread(fullfile(root, 'yunlink_setup.m'));
assert(contains(setupSource, 'nargin == 0'), ...
    'yunlink_setup must support the no-argument wizard.');
assert(contains(setupSource, 'uigetfile'), ...
    'yunlink_setup wizard must use MATLAB file selection.');
assert(contains(setupSource, 'Select bundle folder'', ''Select wheel'', ''Skip'', ''Select bundle folder''') || ...
    contains(setupSource, "'Select bundle folder', 'Select wheel', 'Skip', 'Select bundle folder'"), ...
    'yunlink_setup binding dialog must be a 3-button questdlg with an explicit default.');
assert(contains(setupSource, 'cp314') || contains(setupSource, '3.14'), ...
    'yunlink_setup must reject MATLAB Python 3.14 with a visible message.');
assert(contains(setupSource, '3.13'), ...
    'yunlink_setup must accept Python 3.13.');
assert(contains(setupSource, 'cp313'), ...
    'yunlink_setup must match Python 3.13 wheels.');
assert(contains(setupSource, 'win_amd64'), ...
    'yunlink_setup must pick win_amd64 instead of all Windows wheels.');
assert(contains(setupSource, 'resolve_bundle_dir'), ...
    'yunlink_setup must unwrap a double-nested unzipped bundle folder.');
assert(contains(setupSource, "'**', pattern") || contains(setupSource, "**', pattern"), ...
    'yunlink_setup must search wheels/ recursively.');
assert(contains(fileread(fullfile(root, 'build_toolbox.m')), "MinimumMatlabRelease = 'R2022b'"), ...
    'Toolbox package must declare MATLAB R2022b as the minimum release.');
assert(contains(fileread(fullfile(root, 'yunlink_ensure_python.m')), 'CPython'), ...
    'yunlink_ensure_python must explain MATLAB CPython version errors.');
assert(contains(fileread(fullfile(root, 'yunlink_ensure_python.m')), 'prefdir'), ...
    'yunlink_ensure_python must persist the selected interpreter.');
assert(~contains(setupSource, '3.10+'), ...
    'yunlink_setup must list 3.10-3.13 explicitly.');
assert(~contains(setupSource, 'yunlink_connect('), ...
    'yunlink_setup must not connect to a vehicle.');
assert(contains(setupSource, 'yunlink_examples'), ...
    'yunlink_setup must offer to open the MATLAB example folder.');
exampleOpener = fileread(fullfile(root, 'yunlink_examples.m'));
assert(contains(exampleOpener, 'filebrowser'), ...
    'yunlink_examples must show MATLAB Current Folder.');
assert(contains(exampleOpener, 'ex00_setup.m') || contains(exampleOpener, 'read_state_demo.m'), ...
    'yunlink_examples must surface the setup or read-only demo.');
setupExample = fileread(fullfile(root, 'examples', 'ex00_setup.m'));
assert(contains(setupExample, 'pythonExe') && contains(setupExample, 'bundleDir'), ...
    'ex00_setup.m must let the user fill python and bundle paths.');
assert(contains(fileread(fullfile(root, 'yunlink_setup.m')), 'clean_env_prefix'), ...
    'yunlink_setup must isolate MATLAB library paths when invoking Python.');
assert(contains(fileread(fullfile(root, 'yunlink_setup.m')), 'install_protobuf'), ...
    'yunlink_setup must install protobuf without relying on pip.');
assert(contains(fileread(fullfile(root, 'yunlink_setup.m')), 'getCanonicalPath'), ...
    'yunlink_setup must treat Homebrew python symlinks as the same interpreter.');

userGuide = fileread(fullfile(root, 'README.md'));
assert(contains(userGuide, '双击') && contains(userGuide, '.mltbx'), ...
    'User guide must document double-clicking the .mltbx installer.');
assert(contains(userGuide, 'Add Package Repository'), ...
    'User guide must distinguish package repositories from .mltbx installation.');
assert(contains(userGuide, 'Windows') && contains(userGuide, 'Linux'), ...
    'User guide must cover Windows, macOS, and Linux.');
assert(contains(userGuide, 'ex00_setup.m'), ...
    'User guide must point at ex00_setup.m.');
assert(contains(userGuide, 'R2022b'), ...
    'User guide must require MATLAB R2022b.');
assert(contains(userGuide, 'yunlink'), ...
    'User guide must mention the yunlink 3.10 requirement.');
assert(contains(fileread(fullfile(root, 'developer', 'API.md')), 'yunlink_takeoff'), ...
    'MATLAB developer API must document wrapper calls.');
assert(~contains(userGuide, '/Users/groove'), ...
    'User guide must not include a machine-specific home path.');

packSource = fileread(fullfile(root, 'build_toolbox.m'));
assert(contains(packSource, 'getting_started.html'));
assert(contains(packSource, 'getting_started.m'));
assert(contains(packSource, 'ToolboxFiles'));
assert(contains(packSource, 'vendor'));

demoSource = fileread(fullfile(root, 'examples', 'basic_flight_demo.m'));
assert(contains(demoSource, '会飞') || contains(demoSource, '会发送飞行指令'));
readSource = fileread(fullfile(root, 'examples', 'read_state_demo.m'));
assert(contains(readSource, '不飞') || contains(readSource, '不发送飞行指令'));
discoverSource = fileread(fullfile(root, 'examples', 'ex01_discover.m'));
assert(contains(discoverSource, 'entity_uid'));
assert(contains(discoverSource, 'yunlink.env'));
assert(contains(discoverSource, '防火墙') || contains(discoverSource, 'Windows 安全警报'));
exampleGuide = fileread(fullfile(root, 'examples', 'README.md'));
assert(contains(exampleGuide, 'UDP 9697'));
assert(contains(exampleGuide, '| 编号 |'), 'examples/README.md must have an example table.');
assert(contains(exampleGuide, 'ex00_setup.m') && contains(exampleGuide, 'ex12_live_check.m'));
assert(contains(exampleGuide, '这就是教程') || contains(exampleGuide, '按编号跑'));
assert(contains(userGuide, '按编号') || contains(userGuide, 'example'));
assert(~contains(userGuide, '不提供独立的设备搜索'), ...
    'User guide must not say MATLAB cannot discover Bridges.');
flightSource = fileread(fullfile(root, 'examples', 'ex04_flight_basics.m'));
assert(contains(flightSource, 'm/s') && contains(flightSource, '持续'), ...
    'ex04 must comment translate speed vs duration.');
assert(contains(fileread(fullfile(root, 'yunlink_translate.m')), 'm/s'));
assert(contains(fileread(fullfile(root, 'getting_started.html')), 'ex12_live_check'));
assert(contains(fileread(fullfile(root, 'docs', 'yunlink-matlab-manual.typ')), 'chapters/06-examples.typ'));
assert(contains(fileread(fullfile(root, 'docs', 'chapters', '06-examples.typ')), 'ex00_setup'));
assert(contains(fileread(fullfile(root, 'docs', 'chapters', '08-api.typ')), 'yunlink_translate'));
assert(contains(fileread(fullfile(root, 'docs', 'chapters', '02-prepare.typ')), '命令窗口'));
assert(contains(userGuide, 'yunlink-matlab-manual.pdf'));
assert(contains(userGuide, '从哪里开始') || contains(userGuide, 'yunlink_examples'));
assert(contains(userGuide, 'developer/API.md') || contains(userGuide, 'API.md'));
assert(contains(userGuide, 'typst compile'));
assert(contains(fileread(fullfile(root, 'docs', 'README.md')), 'typst compile'));
assert(contains(fileread(fullfile(root, 'examples', 'yunlink.env.example')), 'YUNLINK_UAV='));
loader = fileread(fullfile(root, 'yunlink_load_example_env.m'));
assert(contains(loader, "'yunlink.env', 'yunlink.env.example'") || contains(loader, "'yunlink.env.example'"));
assert(contains(loader, 'yunlink:MissingEnv'));
liveSource = fileread(fullfile(root, 'yunlink_live_check.m'));
assert(contains(liveSource, 'PASS') && contains(liveSource, 'SKIP'));
assert(contains(liveSource, 'yunlink_takeoff'));
assert(contains(liveSource, 'yunlink_land'));
assert(~contains(liveSource, 'yunlink_waypoints'));
assert(contains(fileread(fullfile(root, 'build_toolbox.m')), 'yunlink.env.example'));
assert(contains(userGuide, 'Windows 安全警报') || contains(userGuide, '专用网络'));

% Parse every wrapper so syntax errors are caught even in a no-device run.
addpath(root);
for index = 1:numel(required)
    [folder, name] = fileparts(required{index}); %#ok<ASGLU>
    assert(exist(name, 'file') == 2, 'MATLAB cannot resolve %s', name);
end
assert(exist('build_toolbox', 'file') == 2, 'MATLAB cannot resolve build_toolbox');
fprintf('YunLink MATLAB smoke checks passed (%d wrappers).\n', numel(required));
